### ISSUE TITLE
Hard-coded Paths in SPRoute

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#160]
SPRoute currently hard-codes the paths for "POWV9.dat" and "POST9.dat". In testing we need to be able to pass where these apps are located as a command line argument though since everything is specified relative to `${BASEINPUT}` in the CMakeLists.

**Comment by insertinterestingnamehere** [comment]
@Michael-JY-He can you look at this one? It's causing some test failures right now. I'm adding the NOT_QUICK flag to the new SPRoute test so you can keep debugging but it won't break the CI builds.

**Comment by Michael-JY-He** [comment]
This two files need to be in the same directory as SPRoute binary. Is there a way to do that in CMake?

**Comment by insertinterestingnamehere** [comment]
Okay, after offline discussion with @Michael-JY-He, it sounds like these files are required for all inputs for SPRoute. Given that it may make sense to symlink them directly into the SPRoute directory at build time provided that BASEINPUT is set. On the other hand, it'd still be nice to just be able to specify them via flags.

**Comment by ddn0** [comment]
+1 for configurable paths. Expecting users to have a full development build to use a program inhibits separate usage.

**Comment by Michael-JY-He** [comment]
Done. Please check if test runs.

**Comment by insertinterestingnamehere** [comment]
I'm still seeing errors for some reason now, even when trying to run tests locally. For example, if I run `BASEINPUT=/net/ohm/export/iss/inputs ./SPRoute "${BASEINPUT}/eda/routing/test.out" --flute "${BASEINPUT}/eda/routing"` it says it couldn't load POWV9.dat.

**Comment by Michael-JY-He** [comment]
The test.gr is wrongly replaced by test.out. They are the same. Please replace test.gr with  /h1/mhe/link/GaloisCpp/build-debug-peltier/lonestar/experimental/SPRoute/test.gr and try again. Thanks.

**Comment by insertinterestingnamehere** [comment]
I've fixed this in our inputs directory and in the small inputs download for CI. I'll confirm that it's working and re-enable the test in CI on Monday.

**Comment by insertinterestingnamehere** [comment]
@Michael-JY-He I'm still seeing an error here. I'm running this as `./SPRoute "/net/ohm/export/iss/inputs/eda/routing/test.gr" --flute "/net/ohm/export/iss/inputs/eda/routing"`. Can you tell me what's still wrong?

**Comment by Michael-JY-He** [comment]
Actually I don't know what is going wrong because I can successfully run on firefly with the same command. Can you show me the message SPRoute prints out?

**Comment by insertinterestingnamehere** [comment]
Here's the full output:

```
LoneStar Benchmark Suite v5.0.0 (unknown)
Copyright (C) 2018 The University of Texas at Austin
http://iss.ices.utexas.edu/galois/

application: SPRoute
A Scalable Parallel global router with a hybrid parallel algorithm which combines net-level parallelism and fine-grain parallelism
http://iss.ices.utexas.edu/?p=projects/galois/benchmarks/SPRoute

 nthreads: 1

Reading /net/ohm/export/iss/inputs/eda/routing/test.gr ...

grid 3 3 2
Layer 0 vertical capacity 0, horizontal capacity 1
Layer 1 vertical capacity 1, horizontal capacity 0
total vertical capacity 1
total horizontal capacity 1
num net 1
the total net number is 1

num of Adjust is 4
# valid nets: 1
# segments: 1
maxDeg:     2

Done getting input
MD: 2, AD: 2.00, #nets: 1, #routed nets: 1
TC is 12

Reading Lookup Table ...
Error in opening /net/ohm/export/iss/inputs/eda/routing/POWV9.dat
```

The full set of commands I'm running after logging in to one of our 40 core machines is:

```
cd Galois
source scripts/iss_load_modules
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j80
cd Lonestar/SPRoute
make test
./SPRoute "/net/ohm/export/iss/inputs/eda/routing/test.gr" --flute "/net/ohm/export/iss/inputs/eda/routing"

**Comment by Michael-JY-He** [comment]
Fixed. Please check.
The path was wrongly added a space in the front of the string. It is weird that it always works on the 56 core machines but fails on 40 core machines.

**Comment by insertinterestingnamehere** [comment]
Yep. That fixed it. I've re-enabled the test in CI. Thanks!
